---
# tasks file for vector-role
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Vector installed or not
      ansible.builtin.command: vector --version
      register: is_installed
      ignore_errors: true

    - name: Install and configure vector on remote host
      when:
        - is_installed is failed
        - ansible_distribution == "CentOS"
      block:
        - name: Get Vector distrib
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
            dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
            mode: '0440'
        - name: Install vector package
          become: true
          ansible.builtin.yum:
            name:
              - vector-{{ vector_version }}-1.x86_64.rpm
        - name: Make vector config file remote host
          ansible.builtin.file:
            path: /etc/vector/vector.toml
            state: touch
            mode: u=rw,g=r,o=r

        - name: Build context vector config file from template
          ansible.builtin.template:
            src: "file/vector.j2"
            dest: "/etc/vector/vector.toml"
            backup: true
            mode: '0640'

        - name: Start vector service
          ansible.builtin.service:
            name: vector
            enabled: true
            daemon_reload: true
            state: started
